package org.example.drools.test;

import org.example.drools.test.domain.Event;

rule "Close event without status change x "
when
    $eventCreated: Event($eventId: eventId, status=="created")
    not(
        Event(
            this != $eventCreated,
            eventId==$eventId,
            status != "created",
            status != "closed",
            this after[0s, 5s] $eventCreated
        )
    )
then
    System.out.println("No status change in 5 secs");
    insert(new Event($eventCreated.getEventId(), "closed", "auto-closed"));
end

rule "Collect closed event"
when
    $eventClosed: Event(status=="closed")
then
    System.out.println("Sending " + $eventClosed + " to notification channel");
    channels['notification-channel'].send($eventClosed);

end